// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_byte_map_out_0

//{"out":["byte","map[string]byte","string"]}
func Test0() map[string]byte {
	var res0 map[string]byte
	return res0
}
