// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint32_array_out_named_0

//{"out":["[4]uint32","[]uint32","uint32"]}
func Test0() (res0 [4]uint32) {
	return res0
}
