// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_out_0

// Test0 does things with [] and returns [string].
func Test0() string {
	var res0 string
	return res0
}
