// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_int8_map_in_0

//{"in":["int8","map[string]int8","string"]}
func Test0(par0 map[string]int8) {
}
