// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_complex128_map_out_named_0

//{"out":["complex128","map[string]complex128","string"]}
func Test0() (res0 map[string]complex128) {
	return res0
}
