// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint16_array_out_named_0

//{"out":["[4]uint16","[]uint16"]}
func Test0() (res0 [4]uint16) {
	return res0
}
