// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex64_array_out_named_0

//{"out":["[4]complex64","[]complex64","complex64"]}
func Test0() (res0 [4]complex64) {
	return res0
}
