// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_int8_map_out_0

//{"out":["int8","map[string]int8","string"]}
func Test0() map[string]int8 {
	var res0 map[string]int8
	return res0
}
