// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_complex128_map_out_named_0

// Test0 does things with [] and returns [map[string]complex128].
func Test0() (res0 map[string]complex128) {
	return res0
}
