// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_bool_out_0

//{"out":["bool","struct{F1 bool; F2 bool \"rgo:\\\"Rname\\\"\"}"]}
func Test0() struct {
	F1 bool
	F2 bool "rgo:\"Rname\""
} {
	var res0 struct {
		F1 bool
		F2 bool "rgo:\"Rname\""
	}
	return res0
}
