// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_int16_map_in_0

//{"in":["int16","map[string]int16","string"]}
func Test0(par0 map[string]int16) {
}
