// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_uint16_out_0

//{"out":["struct{F1 uint16; F2 uint16 \"rgo:\\\"Rname\\\"\"}","uint16"]}
func Test0() struct {
	F1 uint16
	F2 uint16 "rgo:\"Rname\""
} {
	var res0 struct {
		F1 uint16
		F2 uint16 "rgo:\"Rname\""
	}
	return res0
}
