// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint32_slice_in_0

// Test0 does things with [[]uint32] and returns [].
func Test0(par0 []uint32) {
}
