// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_slice_in_0

// Test0 does things with [[]string] and returns [].
func Test0(par0 []string) {
}
