// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_byte_map_in_0

//{"in":["map[string]byte","string","uint8"]}
func Test0(par0 map[string]byte) {
}
