// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uintptr_slice_out_0

//{"out":["[]uintptr","uintptr"]}
func Test0() []uintptr {
	var res0 []uintptr
	return res0
}
