// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package int32_slice_out_named_0

// Test0 does things with [] and returns [[]int32].
func Test0() (res0 []int32) {
	return res0
}
