// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_complex128_in_0

// Test0 does things with [struct{F1 complex128; F2 complex128 "rgo:\"Rname\""}] and returns [].
func Test0(par0 struct {
	F1 complex128
	F2 complex128 "rgo:\"Rname\""
}) {
}
