// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint_slice_out_0

//{"out":["[]uint","uint"]}
func Test0() []uint {
	var res0 []uint
	return res0
}
