// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_byte_in_0

//{"in":["struct{F1 uint8; F2 uint8 \"rgo:\\\"Rname\\\"\"}","uint8"]}
func Test0(par0 struct {
	F1 byte
	F2 byte "rgo:\"Rname\""
}) {
}
