// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_int_map_out_0

//{"out":["int","map[string]int","string"]}
func Test0() map[string]int {
	var res0 map[string]int
	return res0
}
