// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package rune_slice_out_0

//{"out":["[]rune","int32"]}
func Test0() []rune {
	var res0 []rune
	return res0
}
