// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_array_out_named_0

//{"out":["[4]string","[]string","string"]}
func Test0() (res0 [4]string) {
	return res0
}
