// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex128_slice_out_named_0

//{"out":["[]complex128"]}
func Test0() (res0 []complex128) {
	return res0
}
