// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_uint32_in_0

//{"in":["struct{F1 uint32; F2 uint32 \"rgo:\\\"Rname\\\"\"}","uint32"]}
func Test0(par0 struct {
	F1 uint32
	F2 uint32 "rgo:\"Rname\""
}) {
}
