// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package float32_slice_out_named_0

//{"out":["[]float32"]}
func Test0() (res0 []float32) {
	return res0
}
