// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_bool_map_in_0

//{"in":["bool","map[string]bool","string"]}
func Test0(par0 map[string]bool) {
}
