# Code generated by rgnonomic/rgo; DO NOT EDIT.

#' @useDynLib cca

#' cca
#'
#' CCA performs a canonical correlation analysis of the input data x
#' and y, columns of which should be interpretable as two sets of
#' measurements on the same observations (rows).
#' 
#' @param x is a list corresponding to struct{Rows int; Cols int; Data []float64; Stride int}
#' @param y is a list corresponding to struct{Rows int; Cols int; Data []float64; Stride int}
#' @return A structured value containing:
#' @return - a double vector, $ccors
#' @return - a list corresponding to struct{Rows int; Cols int; Data []float64; Stride int}, $pVecs
#' @return - a list corresponding to struct{Rows int; Cols int; Data []float64; Stride int}, $qVecs
#' @return - a list corresponding to struct{Rows int; Cols int; Data []float64; Stride int}, $phiVs
#' @return - a list corresponding to struct{Rows int; Cols int; Data []float64; Stride int}, $psiVs
#' @return - a character vector, $err
#' @seelso <https://godoc.org/github.com/rgonomic/rgo/examples/cca#CCA>
#' @export
cca <- function(x, y) {
	if (!is.list(x)) {
		stop("Argument 'x' must be of type 'list'.")
	}
	if (!is.list(y)) {
		stop("Argument 'y' must be of type 'list'.")
	}
	.Call("cca", x, y, PACKAGE = "cca")
}
