// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_float64_map_out_named_0

//{"out":["float64","map[string]float64","string"]}
func Test0() (res0 map[string]float64) {
	return res0
}
