// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package int8_array_out_0

//{"out":["[4]int8","[]int8"]}
func Test0() [4]int8 {
	var res0 [4]int8
	return res0
}
