// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_bool_map_out_0

// Test0 does things with [] and returns [map[string]bool].
func Test0() map[string]bool {
	var res0 map[string]bool
	return res0
}
