// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_string_in_0

//{"in":["string","struct{F1 string; F2 string \"rgo:\\\"Rname\\\"\"}"]}
func Test0(par0 struct {
	F1 string
	F2 string "rgo:\"Rname\""
}) {
}
