// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_complex128_in_0

//{"in":["complex128","struct{F1 complex128; F2 complex128 \"rgo:\\\"Rname\\\"\"}"]}
func Test0(par0 struct {
	F1 complex128
	F2 complex128 "rgo:\"Rname\""
}) {
}
