// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_float32_map_in_0

//{"in":["float32","map[string]float32","string"]}
func Test0(par0 map[string]float32) {
}
