// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_complex128_out_named_0

// Test0 does things with [] and returns [struct{F1 complex128; F2 complex128 "rgo:\"Rname\""}].
func Test0() (res0 struct {
	F1 complex128
	F2 complex128 "rgo:\"Rname\""
}) {
	return res0
}
