// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package slice_of_slices_0

// Test0 does things with [[][]float64] and returns [[][]float64].
func Test0(par0 [][]float64) [][]float64 {
	var res0 [][]float64
	return res0
}
