// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_rune_map_out_0

//{"out":["int32","map[string]int32","string"]}
func Test0() map[string]rune {
	var res0 map[string]rune
	return res0
}
