// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_complex64_out_0

// Test0 does things with [] and returns [struct{F1 complex64; F2 complex64 "rgo:\"Rname\""}].
func Test0() struct {
	F1 complex64
	F2 complex64 "rgo:\"Rname\""
} {
	var res0 struct {
		F1 complex64
		F2 complex64 "rgo:\"Rname\""
	}
	return res0
}
