// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint_array_out_named_0

// Test0 does things with [] and returns [[4]uint].
func Test0() (res0 [4]uint) {
	return res0
}
