// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_uint8_map_out_0

// Test0 does things with [] and returns [map[string]uint8].
func Test0() map[string]uint8 {
	var res0 map[string]uint8
	return res0
}
