// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_float64_in_0

//{"in":["float64","struct{F1 float64; F2 float64 \"rgo:\\\"Rname\\\"\"}"]}
func Test0(par0 struct {
	F1 float64
	F2 float64 "rgo:\"Rname\""
}) {
}
