// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_complex128_map_in_0

//{"in":["complex128","map[string]complex128","string"]}
func Test0(par0 map[string]complex128) {
}
