// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package byte_slice_in_0

// Test0 does things with [[]byte] and returns [].
func Test0(par0 []byte) {
}
