// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_rune_map_in_0

//{"in":["int32","map[string]int32","string"]}
func Test0(par0 map[string]rune) {
}
