// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package bool_array_out_0

//{"out":["[4]bool","[]bool"]}
func Test0() [4]bool {
	var res0 [4]bool
	return res0
}
