// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package byte_array_out_0

//{"out":["[4]uint8","[]uint8"]}
func Test0() [4]byte {
	var res0 [4]byte
	return res0
}
