// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_int32_in_0

// Test0 does things with [struct{F1 int32; F2 int32 "rgo:\"Rname\""}] and returns [].
func Test0(par0 struct {
	F1 int32
	F2 int32 "rgo:\"Rname\""
}) {
}
