// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex128_array_in_0

//{"in":["[4]complex128","[]complex128"]}
func Test0(par0 [4]complex128) {
}
