// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package int_out_named_0

// Test0 does things with [] and returns [int].
func Test0() (res0 int) {
	return res0
}
