// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package bool_array_out_named_0

//{"out":["[4]bool","[]bool"]}
func Test0() (res0 [4]bool) {
	return res0
}
