// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_array_out_0

// Test0 does things with [] and returns [[4]string].
func Test0() [4]string {
	var res0 [4]string
	return res0
}
