// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uintptr_slice_out_named_0

//{"out":["[]uintptr"]}
func Test0() (res0 []uintptr) {
	return res0
}
