// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package float64_slice_in_0

// Test0 does things with [[]float64] and returns [].
func Test0(par0 []float64) {
}
