// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_float64_map_in_0

//{"in":["float64","map[string]float64","string"]}
func Test0(par0 map[string]float64) {
}
