// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_int8_in_0

//{"in":["int8","struct{F1 int8; F2 int8 \"rgo:\\\"Rname\\\"\"}"]}
func Test0(par0 struct {
	F1 int8
	F2 int8 "rgo:\"Rname\""
}) {
}
