// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_byte_out_0

// Test0 does things with [] and returns [struct{F1 byte; F2 byte "rgo:\"Rname\""}].
func Test0() struct {
	F1 byte
	F2 byte "rgo:\"Rname\""
} {
	var res0 struct {
		F1 byte
		F2 byte "rgo:\"Rname\""
	}
	return res0
}
