// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex128_out_named_0

// Test0 does things with [] and returns [complex128].
func Test0() (res0 complex128) {
	return res0
}
