// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_rune_map_out_0

// Test0 does things with [] and returns [map[string]rune].
func Test0() map[string]rune {
	var res0 map[string]rune
	return res0
}
