// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_rune_map_out_named_0

//{"out":["int32","map[string]rune","string"]}
func Test0() (res0 map[string]rune) {
	return res0
}
