// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package int32_array_out_0

//{"out":["[4]int32","[]int32","int32"]}
func Test0() [4]int32 {
	var res0 [4]int32
	return res0
}
