// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_uintptr_map_in_0

//{"in":["map[string]uintptr","string","uintptr"]}
func Test0(par0 map[string]uintptr) {
}
