// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex128_slice_in_0

//{"in":["[]complex128","complex128"]}
func Test0(par0 []complex128) {
}
