// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package bool_slice_in_0

// Test0 does things with [[]bool] and returns [].
func Test0(par0 []bool) {
}
