// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_float64_map_out_0

// Test0 does things with [] and returns [map[string]float64].
func Test0() map[string]float64 {
	var res0 map[string]float64
	return res0
}
