// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint16_array_out_0

// Test0 does things with [] and returns [[4]uint16].
func Test0() [4]uint16 {
	var res0 [4]uint16
	return res0
}
