// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package rune_array_out_named_0

//{"out":["[4]int32","[]int32"]}
func Test0() (res0 [4]rune) {
	return res0
}
