// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_uint_map_out_0

//{"out":["map[string]uint","string","uint"]}
func Test0() map[string]uint {
	var res0 map[string]uint
	return res0
}
