// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_uint16_map_in_0

//{"in":["map[string]uint16","string","uint16"]}
func Test0(par0 map[string]uint16) {
}
