// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package float64_array_out_named_0

//{"out":["[4]float64","[]float64"]}
func Test0() (res0 [4]float64) {
	return res0
}
