// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_complex64_map_out_named_0

//{"out":["complex64","map[string]complex64","string"]}
func Test0() (res0 map[string]complex64) {
	return res0
}
