// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package byte_slice_out_0

// Test0 does things with [] and returns [[]byte].
func Test0() []byte {
	var res0 []byte
	return res0
}
