// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_int32_out_named_0

// Test0 does things with [] and returns [struct{F1 int32; F2 int32 "rgo:\"Rname\""}].
func Test0() (res0 struct {
	F1 int32
	F2 int32 "rgo:\"Rname\""
}) {
	return res0
}
