// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_complex64_out_named_0

//{"out":["complex64","struct{F1 complex64; F2 complex64 \"rgo:\\\"Rname\\\"\"}"]}
func Test0() (res0 struct {
	F1 complex64
	F2 complex64 "rgo:\"Rname\""
}) {
	return res0
}
