// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex64_slice_out_named_0

// Test0 does things with [] and returns [[]complex64].
func Test0() (res0 []complex64) {
	return res0
}
