// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package int16_out_named_0

// Test0 does things with [] and returns [int16].
func Test0() (res0 int16) {
	return res0
}
