// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package float64_out_0

// Test0 does things with [] and returns [float64].
func Test0() float64 {
	var res0 float64
	return res0
}
