// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I/usr/share/R/include generate.go

package sexp

type sxpinfo struct {
	Gp        uint16
	Pad_cgo_0 [2]byte
	Named     uint16
	Pad_cgo_1 [2]byte
}

type sexprec struct {
	Sxpinfo   sxpinfo
	Attrib    *sexprec
	Next_node *sexprec
	Prev_node *sexprec
	U         [24]byte
}

type (
	vector_sexprec struct {
		Sxpinfo   sxpinfo
		Attrib    *sexprec
		Next_node *sexprec
		Prev_node *sexprec
		Vecsxp    vecsxp
	}
	vecsxp struct {
		Length     int64
		Truelength int64
	}
)

type (
	prim_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		Prim_sxp        primsxp
		Pad_cgo_0       [4]byte
	}
	primsxp struct {
		Offset int32
	}
)

type (
	sym_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		Sym_sxp         symsxp
	}
	symsxp struct {
		Pname    *sexprec
		Value    *sexprec
		Internal *sexprec
	}
)

type (
	list_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		List_sxp        listsxp
	}
	listsxp struct {
		Carval *sexprec
		Cdrval *sexprec
		Tagval *sexprec
	}
)

type (
	env_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		Env_sxp         envsxp
	}
	envsxp struct {
		Frame   *sexprec
		Enclos  *sexprec
		Hashtab *sexprec
	}
)

type (
	clo_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		Clos_sxp        closxp
	}
	closxp struct {
		Formals *sexprec
		Body    *sexprec
		Env     *sexprec
	}
)

type (
	prom_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		Prom_sxp        promsxp
	}
	promsxp struct {
		Value *sexprec
		Expr  *sexprec
		Env   *sexprec
	}
)

const (
	NILSXP     SEXPType = 0x0
	SYMSXP     SEXPType = 0x1
	LISTSXP    SEXPType = 0x2
	CLOSXP     SEXPType = 0x3
	ENVSXP     SEXPType = 0x4
	PROMSXP    SEXPType = 0x5
	LANGSXP    SEXPType = 0x6
	SPECIALSXP SEXPType = 0x7
	BUILTINSXP SEXPType = 0x8
	CHARSXP    SEXPType = 0x9
	LGLSXP     SEXPType = 0xa
	INTSXP     SEXPType = 0xd
	REALSXP    SEXPType = 0xe
	CPLXSXP    SEXPType = 0xf
	STRSXP     SEXPType = 0x10
	DOTSXP     SEXPType = 0x11
	ANYSXP     SEXPType = 0x12
	VECSXP     SEXPType = 0x13
	EXPRSXP    SEXPType = 0x14
	BCODESXP   SEXPType = 0x15
	EXTPTRSXP  SEXPType = 0x16
	WEAKREFSXP SEXPType = 0x17
	RAWSXP     SEXPType = 0x18
	S4SXP      SEXPType = 0x19
	NEWSXP     SEXPType = 0x1e
	FREESXP    SEXPType = 0x1f
	FUNSXP     SEXPType = 0x63
)
