// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I/usr/share/R/include sxptypes.go

package sexp

const (
	NILSXP     Type = 0x0
	SYMSXP     Type = 0x1
	LISTSXP    Type = 0x2
	CLOSXP     Type = 0x3
	ENVSXP     Type = 0x4
	PROMSXP    Type = 0x5
	LANGSXP    Type = 0x6
	SPECIALSXP Type = 0x7
	BUILTINSXP Type = 0x8
	CHARSXP    Type = 0x9
	LGLSXP     Type = 0xa
	INTSXP     Type = 0xd
	REALSXP    Type = 0xe
	CPLXSXP    Type = 0xf
	STRSXP     Type = 0x10
	DOTSXP     Type = 0x11
	ANYSXP     Type = 0x12
	VECSXP     Type = 0x13
	EXPRSXP    Type = 0x14
	BCODESXP   Type = 0x15
	EXTPTRSXP  Type = 0x16
	WEAKREFSXP Type = 0x17
	RAWSXP     Type = 0x18
	S4SXP      Type = 0x19
	NEWSXP     Type = 0x1e
	FREESXP    Type = 0x1f
	FUNSXP     Type = 0x63
)
