// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I/usr/share/R/include generate.go

package sexp

type sxpinfo struct {
	Gp        uint16
	Pad_cgo_0 [2]byte
	Named     uint16
	Pad_cgo_1 [2]byte
}

type sexprec struct {
	Sxpinfo   sxpinfo
	Attrib    *sexprec
	Next_node *sexprec
	Prev_node *sexprec
	U         [24]byte
}

type (
	vector_sexprec struct {
		Sxpinfo   sxpinfo
		Attrib    *sexprec
		Next_node *sexprec
		Prev_node *sexprec
		Vecsxp    vecsxp
	}
	vecsxp struct {
		Length     int64
		Truelength int64
	}
)

type (
	prim_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		Prim_sxp        primsxp
		Pad_cgo_0       [4]byte
	}
	primsxp struct {
		Offset int32
	}
)

type (
	sym_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		Sym_sxp         symsxp
	}
	symsxp struct {
		Pname    *sexprec
		Value    *sexprec
		Internal *sexprec
	}
)

type (
	list_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		List_sxp        listsxp
	}
	listsxp struct {
		Carval *sexprec
		Cdrval *sexprec
		Tagval *sexprec
	}
)

type (
	env_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		Env_sxp         envsxp
	}
	envsxp struct {
		Frame   *sexprec
		Enclos  *sexprec
		Hashtab *sexprec
	}
)

type (
	clo_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		Clos_sxp        closxp
	}
	closxp struct {
		Formals *sexprec
		Body    *sexprec
		Env     *sexprec
	}
)

type (
	prom_sexprec struct {
		Sxpinfo         sxpinfo
		Attrib          *sexprec
		Gengc_next_node *sexprec
		Gengc_prev_node *sexprec
		Prom_sxp        promsxp
	}
	promsxp struct {
		Value *sexprec
		Expr  *sexprec
		Env   *sexprec
	}
)

const (
	NILSXP     Type = 0x0
	SYMSXP     Type = 0x1
	LISTSXP    Type = 0x2
	CLOSXP     Type = 0x3
	ENVSXP     Type = 0x4
	PROMSXP    Type = 0x5
	LANGSXP    Type = 0x6
	SPECIALSXP Type = 0x7
	BUILTINSXP Type = 0x8
	CHARSXP    Type = 0x9
	LGLSXP     Type = 0xa
	INTSXP     Type = 0xd
	REALSXP    Type = 0xe
	CPLXSXP    Type = 0xf
	STRSXP     Type = 0x10
	DOTSXP     Type = 0x11
	ANYSXP     Type = 0x12
	VECSXP     Type = 0x13
	EXPRSXP    Type = 0x14
	BCODESXP   Type = 0x15
	EXTPTRSXP  Type = 0x16
	WEAKREFSXP Type = 0x17
	RAWSXP     Type = 0x18
	S4SXP      Type = 0x19
	NEWSXP     Type = 0x1e
	FREESXP    Type = 0x1f
	FUNSXP     Type = 0x63
)
