// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_complex64_in_0

//{"in":["complex128","complex64","struct{F1 complex64; F2 complex64 \"rgo:\\\"Rname\\\"\"}"]}
func Test0(par0 struct {
	F1 complex64
	F2 complex64 "rgo:\"Rname\""
}) {
}
