// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package rune_slice_out_named_0

// Test0 does things with [] and returns [[]rune].
func Test0() (res0 []rune) {
	return res0
}
