// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_rune_in_0

//{"in":["int32","struct{F1 rune; F2 rune \"rgo:\\\"Rname\\\"\"}"]}
func Test0(par0 struct {
	F1 rune
	F2 rune "rgo:\"Rname\""
}) {
}
