// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex128_in_0

// Test0 does things with [complex128] and returns [].
func Test0(par0 complex128) {
}
