// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_uintptr_out_0

//{"out":["struct{F1 uintptr; F2 uintptr \"rgo:\\\"Rname\\\"\"}","uintptr"]}
func Test0() struct {
	F1 uintptr
	F2 uintptr "rgo:\"Rname\""
} {
	var res0 struct {
		F1 uintptr
		F2 uintptr "rgo:\"Rname\""
	}
	return res0
}
