// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_int_map_in_0

//{"in":["int","map[string]int","string"]}
func Test0(par0 map[string]int) {
}
