// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex64_array_in_0

//{"in":["[4]complex64","[]complex64","complex128","complex64"]}
func Test0(par0 [4]complex64) {
}
