// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package int16_out_0

// Test0 does things with [] and returns [int16].
func Test0() int16 {
	var res0 int16
	return res0
}
