// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uintptr_array_in_0

//{"in":["[4]uintptr","[]uintptr","uintptr"]}
func Test0(par0 [4]uintptr) {
}
