// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package float32_out_named_0

// Test0 does things with [] and returns [float32].
func Test0() (res0 float32) {
	return res0
}
