// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_string_map_out_named_0

//{"out":["map[string]string","string"]}
func Test0() (res0 map[string]string) {
	return res0
}
