// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_string_map_in_0

//{"in":["map[string]string","string"]}
func Test0(par0 map[string]string) {
}
