// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_uintptr_map_out_0

//{"out":["map[string]uintptr","string","uintptr"]}
func Test0() map[string]uintptr {
	var res0 map[string]uintptr
	return res0
}
