// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_uint32_out_0

//{"out":["struct{F1 uint32; F2 uint32 \"rgo:\\\"Rname\\\"\"}","uint32"]}
func Test0() struct {
	F1 uint32
	F2 uint32 "rgo:\"Rname\""
} {
	var res0 struct {
		F1 uint32
		F2 uint32 "rgo:\"Rname\""
	}
	return res0
}
