// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint32_slice_out_named_0

// Test0 does things with [] and returns [[]uint32].
func Test0() (res0 []uint32) {
	return res0
}
