// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_float64_in_0

// Test0 does things with [struct{F1 float64; F2 float64 "rgo:\"Rname\""}] and returns [].
func Test0(par0 struct {
	F1 float64
	F2 float64 "rgo:\"Rname\""
}) {
}
