// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package float64_slice_out_named_0

//{"out":["[]float64","float64"]}
func Test0() (res0 []float64) {
	return res0
}
