# Code generated by rgnonomic/rgo; DO NOT EDIT.

#' @useDynLib sexp

#' print_sexp
#'
#' PrintSEXP prints the SEXP value passed to it along with any names it has
#' and returns it unaltered. If the value is an atomic vector, its contents
#' are printed.
#' 
#' @param p is an arbitrary value
#' @return An arbitrary value
#' @seelso <https://godoc.org/github.com/rgonomic/rgo/examples/sexp#PrintSEXP>
#' @export
print_sexp <- function(p) {
	.Call("print_sexp", p, PACKAGE = "sexp")
}

#' gophers
#'
#' Gophers returns n gophers with name attributes.
#' 
#' @param n is a scalar integer
#' @return An arbitrary value
#' @seelso <https://godoc.org/github.com/rgonomic/rgo/examples/sexp#Gophers>
#' @export
gophers <- function(n) {
	if (!is.integer(n)) {
		stop("Argument 'n' must be of type 'integer'.")
	}
	if (length(n) != 1) {
		stop("Argument 'n' must have 1 element.")
	}
	.Call("gophers", n, PACKAGE = "sexp")
}
