# Code generated by rgnonomic/rgo; DO NOT EDIT.

#' @useDynLib sexp

#' print_sexp
#'
#' PrintSEXP prints the SEXP value passed to it and returns it unaltered.
#' If the value is an atomic vector, its contents are printed.
#' 
#' @param p is a scalar SEXP
#' @return A scalar SEXP
#' @seelso <https://godoc.org/github.com/rgonomic/rgo/examples/sexp#PrintSEXP>
#' @export
print_sexp <- function(p) {
	.Call("print_sexp", p, PACKAGE = "sexp")
}
