// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_uint16_map_out_0

//{"out":["map[string]uint16","string","uint16"]}
func Test0() map[string]uint16 {
	var res0 map[string]uint16
	return res0
}
