// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_complex64_map_in_0

//{"in":["complex128","complex64","map[string]complex64","string"]}
func Test0(par0 map[string]complex64) {
}
