// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_bool_map_out_named_0

//{"out":["bool","map[string]bool","string"]}
func Test0() (res0 map[string]bool) {
	return res0
}
