// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint16_out_named_0

// Test0 does things with [] and returns [uint16].
func Test0() (res0 uint16) {
	return res0
}
