// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint_array_out_0

//{"out":["[4]uint","[]uint"]}
func Test0() [4]uint {
	var res0 [4]uint
	return res0
}
