// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_int32_map_out_named_0

//{"out":["int32","map[string]int32","string"]}
func Test0() (res0 map[string]int32) {
	return res0
}
