// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_float32_in_0

//{"in":["float32","struct{F1 float32; F2 float32 \"rgo:\\\"Rname\\\"\"}"]}
func Test0(par0 struct {
	F1 float32
	F2 float32 "rgo:\"Rname\""
}) {
}
