// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex128_out_0

// Test0 does things with [] and returns [complex128].
func Test0() complex128 {
	var res0 complex128
	return res0
}
