// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package float32_array_in_0

//{"in":["[4]float32","[]float32","float32"]}
func Test0(par0 [4]float32) {
}
