// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_uintptr_in_0

//{"in":["struct{F1 uintptr; F2 uintptr \"rgo:\\\"Rname\\\"\"}","uintptr"]}
func Test0(par0 struct {
	F1 uintptr
	F2 uintptr "rgo:\"Rname\""
}) {
}
