// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_int_in_0

//{"in":["int","struct{F1 int; F2 int \"rgo:\\\"Rname\\\"\"}"]}
func Test0(par0 struct {
	F1 int
	F2 int "rgo:\"Rname\""
}) {
}
