// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package int16_slice_out_0

//{"out":["[]int16","int16"]}
func Test0() []int16 {
	var res0 []int16
	return res0
}
