// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_uint_map_in_0

//{"in":["map[string]uint","string","uint"]}
func Test0(par0 map[string]uint) {
}
