// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_byte_map_out_named_0

// Test0 does things with [] and returns [map[string]byte].
func Test0() (res0 map[string]byte) {
	return res0
}
