// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_string_map_in_0

// Test0 does things with [map[string]string] and returns [].
func Test0(par0 map[string]string) {
}
