// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint8_slice_out_named_0

// Test0 does things with [] and returns [[]uint8].
func Test0() (res0 []uint8) {
	return res0
}
