// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_uint32_map_in_0

//{"in":["map[string]uint32","string","uint32"]}
func Test0(par0 map[string]uint32) {
}
