// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uintptr_array_out_0

//{"out":["[4]uintptr","[]uintptr"]}
func Test0() [4]uintptr {
	var res0 [4]uintptr
	return res0
}
