// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_slice_out_named_0

// Test0 does things with [] and returns [[]string].
func Test0() (res0 []string) {
	return res0
}
