// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package byte_array_out_named_0

//{"out":["[4]uint8","[]uint8","uint8"]}
func Test0() (res0 [4]byte) {
	return res0
}
