// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_array_in_0

// Test0 does things with [[4]string] and returns [].
func Test0(par0 [4]string) {
}
