// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_int8_out_named_0

//{"out":["int8","struct{F1 int8; F2 int8 \"rgo:\\\"Rname\\\"\"}"]}
func Test0() (res0 struct {
	F1 int8
	F2 int8 "rgo:\"Rname\""
}) {
	return res0
}
