// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_complex64_map_out_named_0

// Test0 does things with [] and returns [map[string]complex64].
func Test0() (res0 map[string]complex64) {
	return res0
}
