// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint_slice_in_0

// Test0 does things with [[]uint] and returns [].
func Test0(par0 []uint) {
}
