// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint_slice_out_0

// Test0 does things with [] and returns [[]uint].
func Test0() []uint {
	var res0 []uint
	return res0
}
