// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package int32_slice_out_0

//{"out":["[]int32","int32"]}
func Test0() []int32 {
	var res0 []int32
	return res0
}
