// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package rune_array_out_0

// Test0 does things with [] and returns [[4]rune].
func Test0() [4]rune {
	var res0 [4]rune
	return res0
}
