// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package uint8_array_in_0

// Test0 does things with [[4]uint8] and returns [].
func Test0(par0 [4]uint8) {
}
