// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package bool_out_0

// Test0 does things with [] and returns [bool].
func Test0() bool {
	var res0 bool
	return res0
}
