// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package map_of_slices_0

// Test0 does things with [map[string][]float64] and returns [map[string][]float64].
func Test0(par0 map[string][]float64) map[string][]float64 {
	var res0 map[string][]float64
	return res0
}
