// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package float32_slice_out_0

// Test0 does things with [] and returns [[]float32].
func Test0() []float32 {
	var res0 []float32
	return res0
}
