// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex128_array_out_named_0

// Test0 does things with [] and returns [[4]complex128].
func Test0() (res0 [4]complex128) {
	return res0
}
