// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package complex64_array_out_0

// Test0 does things with [] and returns [[4]complex64].
func Test0() [4]complex64 {
	var res0 [4]complex64
	return res0
}
