// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_int32_map_out_0

// Test0 does things with [] and returns [map[string]int32].
func Test0() map[string]int32 {
	var res0 map[string]int32
	return res0
}
