// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_int8_map_out_named_0

//{"out":["int8","map[string]int8","string"]}
func Test0() (res0 map[string]int8) {
	return res0
}
