# Code generated by rgnonomic/rgo; DO NOT EDIT.

#' @useDynLib ioutil

#' read_file
#'
#' ReadFile reads the file named by filename and returns the contents.
#' A successful call returns err == nil, not err == EOF. Because ReadFile
#' reads the whole file, it does not treat an EOF from Read as an error
#' to be reported.
#' 
#' @param filename is a scalar character
#' @return A structured value containing:
#' @return - a raw vector, $r0
#' @return - a character vector, $r1
#' @seelso <https://godoc.org/io/ioutil#ReadFile>
#' @export
read_file <- function(filename) {
	if (!is.character(filename)) {
		stop("Argument 'filename' must be of type 'character'.")
	}
	if (length(filename) != 1) {
		stop("Argument 'filename' must have 1 element.")
	}
	.Call("read_file", filename, PACKAGE = "ioutil")
}
