// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_uint_in_0

// Test0 does things with [struct{F1 uint; F2 uint "rgo:\"Rname\""}] and returns [].
func Test0(par0 struct {
	F1 uint
	F2 uint "rgo:\"Rname\""
}) {
}
