// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_uint_out_0

//{"out":["struct{F1 uint; F2 uint \"rgo:\\\"Rname\\\"\"}","uint"]}
func Test0() struct {
	F1 uint
	F2 uint "rgo:\"Rname\""
} {
	var res0 struct {
		F1 uint
		F2 uint "rgo:\"Rname\""
	}
	return res0
}
