// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_uint8_in_0

// Test0 does things with [struct{F1 uint8; F2 uint8 "rgo:\"Rname\""}] and returns [].
func Test0(par0 struct {
	F1 uint8
	F2 uint8 "rgo:\"Rname\""
}) {
}
