// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_float32_map_out_0

// Test0 does things with [] and returns [map[string]float32].
func Test0() map[string]float32 {
	var res0 map[string]float32
	return res0
}
