// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package byte_array_out_named_0

// Test0 does things with [] and returns [[4]byte].
func Test0() (res0 [4]byte) {
	return res0
}
