// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_rune_map_in_0

// Test0 does things with [map[string]rune] and returns [].
func Test0(par0 map[string]rune) {
}
