// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_int_out_named_0

//{"out":["int","struct{F1 int; F2 int \"rgo:\\\"Rname\\\"\"}"]}
func Test0() (res0 struct {
	F1 int
	F2 int "rgo:\"Rname\""
}) {
	return res0
}
