// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package bool_slice_out_named_0

//{"out":["[]bool","bool"]}
func Test0() (res0 []bool) {
	return res0
}
