// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_int_out_0

// Test0 does things with [] and returns [struct{F1 int; F2 int "rgo:\"Rname\""}].
func Test0() struct {
	F1 int
	F2 int "rgo:\"Rname\""
} {
	var res0 struct {
		F1 int
		F2 int "rgo:\"Rname\""
	}
	return res0
}
