// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_complex64_map_in_0

// Test0 does things with [map[string]complex64] and returns [].
func Test0(par0 map[string]complex64) {
}
