// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_string_map_out_named_0

// Test0 does things with [] and returns [map[string]string].
func Test0() (res0 map[string]string) {
	return res0
}
