// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_int16_map_out_named_0

//{"out":["int16","map[string]int16","string"]}
func Test0() (res0 map[string]int16) {
	return res0
}
