// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package byte_out_named_0

// Test0 does things with [] and returns [byte].
func Test0() (res0 byte) {
	return res0
}
