// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_int_map_out_0

// Test0 does things with [] and returns [map[string]int].
func Test0() map[string]int {
	var res0 map[string]int
	return res0
}
