// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package int16_slice_in_0

// Test0 does things with [[]int16] and returns [].
func Test0(par0 []int16) {
}
