// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_float32_map_out_named_0

//{"out":["float32","map[string]float32","string"]}
func Test0() (res0 map[string]float32) {
	return res0
}
