// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package struct_string_out_named_0

// Test0 does things with [] and returns [struct{F1 string; F2 string "rgo:\"Rname\""}].
func Test0() (res0 struct {
	F1 string
	F2 string "rgo:\"Rname\""
}) {
	return res0
}
