// Code generated by "go generate github.com/rgonomic/rgo/internal/pkg/testdata"; DO NOT EDIT.

package string_slice_out_0

//{"out":["[]string","string"]}
func Test0() []string {
	var res0 []string
	return res0
}
